LTO_ENABLE = yes
VIA_ENABLE = yes
VIAL_ENABLE = yes

MOUSEKEY_ENABLE = no
TAP_DANCE_ENABLE = no
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no
REPEAT_KEY_ENABLE = no
QMK_SETTINGS = no
CAPS_WORD_ENABLE = no
LAYER_LOCK_ENABLE = no

VIAL_INSECURE = yes